[workspace]
members = [
	"wonnx",
	"wonnx-py",
	"wonnx-cli",
	"wonnx-preprocessing",
	"wonnx-wasm"
]

default-members = ["wonnx", "wonnx-cli"]
resolver = "2"

[patch.crates-io]
wonnx = { path = "./wonnx" }
wonnx-preprocessing = { path = "./wonnx-preprocessing" }