name: Check ONNX Backend using Python automated test

on:
  push:
    branches: [master, staging]
  pull_request:

jobs:
  build_manylinux:
    name: Create Release manylinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish wheel
        uses: docker://konstin2/maturin:latest
        with:
          entrypoint: /bin/bash
          args: .github/test_onnx_backend.sh
