name: Create macos universal2 python release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching wonnx-py-v*

env:
  RUST_BACKTRACE: 1
  RUST_VERSION: 1.66

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
      - name: Setup universal2 targets for Rust
        run: |
          rustup target add aarch64-apple-darwin
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare maturin publish
        shell: bash
        run: |
          cd wonnx-py
      - name: maturin publish
        uses: messense/maturin-action@v1
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASS }}
        with:
          maturin-version: 0.12.1
          command: publish
          args: -m wonnx-py/Cargo.toml --no-sdist --universal2 -o wheels -i python -u __token__
